---
language: python
services: docker
python: "3.7"

env:
  global:
    - ROLE_NAME: rpimonitor
  matrix:
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

install:
  - pip install --upgrade pip poetry
  - poetry install -v

script:
  - pwd
  - poetry shell
  - echo "Executing CI for $ROLE_NAME"
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
