---
language: python
services: docker

env:
  global:
    - ROLE_NAME: rpimonitor
  matrix:
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
