---
language: python
services: docker
python: "3.7"

env:
  global:
    - ROLE_NAME: rpimonitor
  matrix:
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

install:
  - pip install --upgrade pip poetry
  - poetry install -v

before_script:
  # Use actual Ansible Galaxy role name for the project directory. <-- Credits to geerlingguy
  - cd ../
  - mv ansible-role-$ROLE_NAME kitos9112.$ROLE_NAME
  - cd kitos9112.$ROLE_NAME
  - echo "Executing CI for $ROLE_NAME"

script:
  # Executing tests
  - poetry run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
