---
# tasks file for debuglevel.rpimonitor
- name: Install dirmgt acting as pre-requisite
  apt:
    name: dirmngr
    update_cache: yes

- name: Install RPi-monitor public GPG key
  apt_key:
    keyserver: "{{ rpimonitor_apt_key_server }}"
    id: "{{ rpimonitor_apt_key_id }}"

- name: Install APT repository
  apt_repository:
    repo: "{{ rpimonitor_repo }}"
    filename: rpimonitor

- name: Create rpimonitor group service account
  group:
    name: "{{ rpimonitor_group }}"
    system: yes

- name: Create rpimonitor user service account
  user:
    name: "{{ rpimonitor_user }}"
    create_home: no
    system: yes
    group: "{{ rpimonitor_group }}"

- name: Install RPI-Monitor
  apt:
    update_cache: yes
    name: rpimonitor
  notify:
    - Update rpi-monitor
    - Install auto-package update

- name: Ensure embedded web server is not started
  ansible.builtin.lineinfile:
    path: "{{ rpimonitor_daemon_conf_file }}"
    regexp: '^daemon.noserver'
    insertafter: '#daemon.noserver'
    line: daemon.noserver=1

- name: Ensure service group is used
  ansible.builtin.lineinfile:
    path: "{{ rpimonitor_daemon_conf_file }}"
    regexp: '^daemon.group'
    insertafter: '#daemon.group'
    line: daemon.group={{ rpimonitor_group }}

- name: Ensure service user is used
  ansible.builtin.lineinfile:
    path: "{{ rpimonitor_daemon_conf_file }}"
    regexp: '^daemon.user'
    insertafter: '#daemon.user'
    line: daemon.user={{ rpimonitor_user }}