---
- name: Update packages status
  become: yes
  command:
    cmd: /etc/init.d/rpimonitor update

- name: Ensure packages-status APT-Hook
  become: yes
  command:
    cmd: /etc/init.d/rpimonitor install_auto_package_status_update