---
- name: Update packages status
  become: true
  command:
    cmd: /etc/init.d/rpimonitor update

- name: Ensure packages-status APT-Hook
  become: true
  command:
    cmd: /etc/init.d/rpimonitor install_auto_package_status_update

- name: Restart RPi-Monitor
  become: true
  service:
    name: rpimonitor
    state: restarted